export const adminResourceGroups = Object.freeze({
  catalog: 'Catalog',
  customers: 'Customers',
  orders: 'Orders',
  shipping: 'Shipping',
  marketing: 'Marketing',
  media: 'Media',
  store: 'Online Store',
  requests: 'Requests',
  system: 'System',
});

const resource = (key, options) => ({
  key,
  supportsList: true,
  supportsDetail: true,
  supportsWrite: false,
  searchable: true,
  sortable: true,
  filterable: true,
  ...options,
});

export const adminResources = Object.freeze({
  stores: resource('stores', {
    title: 'Stores',
    singular: 'store',
    description: 'Markets and storefront records exposed by DRF.',
    group: 'store',
    icon: 'fa-solid fa-store',
    endpoint: '/stores/',
    columns: [['name', 'Store'], ['username', 'Username'], ['domain', 'Domain'], ['status', 'Status']],
  }),
  customers: resource('customers', {
    title: 'Customers',
    singular: 'customer',
    description: 'Customer profiles from customer-info.',
    group: 'customers',
    icon: 'fa-solid fa-users',
    endpoint: '/customer-info/',
    columns: [['name', 'Customer'], ['email', 'Email'], ['phone', 'Phone'], ['status', 'Status']],
  }),
  'customer-addresses': resource('customer-addresses', {
    title: 'Customer Addresses',
    singular: 'customer address',
    description: 'Saved delivery addresses connected to customers.',
    group: 'customers',
    icon: 'fa-solid fa-location-dot',
    endpoint: '/customer-addresses/',
    columns: [['name', 'Address'], ['customer', 'Customer'], ['city', 'City'], ['country', 'Country']],
  }),
  categories: resource('categories', {
    title: 'Categories',
    singular: 'category',
    description: 'Live catalog taxonomy and merchandising structure.',
    group: 'catalog',
    icon: 'fa-solid fa-grid-2',
    endpoint: '/categories/',
    columns: [['name', 'Category'], ['slug', 'Slug'], ['count', 'Products'], ['status', 'Status']],
  }),
  collections: resource('collections', {
    title: 'Collections',
    singular: 'collection',
    description: 'Curated product groupings from DRF collections.',
    group: 'catalog',
    icon: 'fa-solid fa-layer-group',
    endpoint: '/collections/',
    columns: [['name', 'Collection'], ['slug', 'Slug'], ['count', 'Products'], ['status', 'Status']],
  }),
  brands: resource('brands', {
    title: 'Brands',
    singular: 'brand',
    description: 'Brand identities currently exposed by Osimart.',
    group: 'catalog',
    icon: 'fa-solid fa-copyright',
    endpoint: '/brands/',
    columns: [['name', 'Brand'], ['slug', 'Slug'], ['count', 'Products'], ['status', 'Status']],
  }),
  'variant-types': resource('variant-types', {
    title: 'Variant Types',
    singular: 'variant type',
    description: 'Variant attributes such as color, size, storage, and configuration.',
    group: 'catalog',
    icon: 'fa-solid fa-sliders',
    endpoint: '/variant-types/',
    columns: [['name', 'Variant Type'], ['slug', 'Slug'], ['count', 'Values'], ['status', 'Status']],
  }),
  products: resource('products', {
    title: 'Products',
    singular: 'product',
    description: 'Search and inspect the live Osimart catalog.',
    group: 'catalog',
    icon: 'fa-solid fa-box',
    endpoint: '/products/',
    columns: [['name', 'Product'], ['category', 'Category'], ['brand', 'Brand'], ['price', 'Price'], ['stock', 'Stock'], ['status', 'Status']],
    exportable: true,
  }),
  'product-variants': resource('product-variants', {
    title: 'Product Variants',
    singular: 'product variant',
    description: 'Sellable product options and stock records.',
    group: 'catalog',
    icon: 'fa-solid fa-boxes-stacked',
    endpoint: '/product-variants/',
    columns: [['name', 'Variant'], ['sku', 'SKU'], ['price', 'Price'], ['stock', 'Stock'], ['status', 'Status']],
    exportable: true,
  }),
  'product-notification-requests': resource('product-notification-requests', {
    title: 'Product Notification Requests',
    singular: 'notification request',
    description: 'Back-in-stock and product notification requests.',
    group: 'requests',
    icon: 'fa-regular fa-bell',
    endpoint: '/product-notification-requests/',
    columns: [['name', 'Request'], ['email', 'Email'], ['product', 'Product'], ['status', 'Status']],
  }),
  wishlist: resource('wishlist', {
    title: 'Wishlist',
    singular: 'wishlist item',
    description: 'Customer wishlist records exposed by DRF.',
    group: 'customers',
    icon: 'fa-regular fa-heart',
    endpoint: '/wishlist/',
    supportsDetail: false,
    columns: [['name', 'Wishlist Item'], ['customer', 'Customer'], ['product', 'Product'], ['status', 'Status']],
  }),
  cart: resource('cart', {
    title: 'Cart',
    singular: 'cart',
    description: 'Current cart view endpoint for the scoped store/customer session.',
    group: 'orders',
    icon: 'fa-solid fa-cart-shopping',
    endpoint: '/cart/view/',
    supportsDetail: false,
    columns: [['name', 'Cart'], ['customer', 'Customer'], ['total', 'Total'], ['status', 'Status']],
  }),
  'payment-methods': resource('payment-methods', {
    title: 'Payment Methods',
    singular: 'payment method',
    description: 'Configured payment method records.',
    group: 'store',
    icon: 'fa-regular fa-credit-card',
    endpoint: '/payment-methods/',
    columns: [['name', 'Payment Method'], ['type', 'Type'], ['status', 'Status']],
  }),
  'available-payment-methods': resource('available-payment-methods', {
    title: 'Available Payment Methods',
    singular: 'available payment method',
    description: 'Payment methods currently available for checkout.',
    group: 'store',
    icon: 'fa-solid fa-money-check',
    endpoint: '/available-payment-methods/',
    columns: [['name', 'Payment Method'], ['type', 'Type'], ['status', 'Status']],
  }),
  'shipping-countries': resource('shipping-countries', {
    title: 'Shipping Countries',
    singular: 'shipping country',
    description: 'Supported delivery destinations, zones, and availability rules.',
    group: 'shipping',
    icon: 'fa-solid fa-earth-americas',
    endpoint: '/shippingcountries/',
    columns: [['name', 'Country'], ['code', 'Code'], ['price', 'Shipping'], ['status', 'Status']],
  }),
  promotions: resource('promotions', {
    title: 'Promo Codes',
    singular: 'promo code',
    description: 'Promo code campaigns, limits, and schedules.',
    group: 'marketing',
    icon: 'fa-solid fa-tags',
    endpoint: '/promocodes/',
    columns: [['name', 'Promo Code'], ['discount', 'Discount'], ['period', 'Period'], ['status', 'Status']],
  }),
  'free-deliveries': resource('free-deliveries', {
    title: 'Free Deliveries',
    singular: 'free delivery',
    description: 'Free delivery offers and thresholds.',
    group: 'marketing',
    icon: 'fa-solid fa-truck-fast',
    endpoint: '/freedeliveries/',
    columns: [['name', 'Offer'], ['discount', 'Value'], ['period', 'Period'], ['status', 'Status']],
  }),
  checkout: resource('checkout', {
    title: 'Checkout',
    singular: 'checkout',
    description: 'Checkout records exposed by DRF.',
    group: 'orders',
    icon: 'fa-solid fa-cash-register',
    endpoint: '/checkout/',
    columns: [['name', 'Checkout'], ['customer', 'Customer'], ['total', 'Total'], ['status', 'Status']],
  }),
  orders: resource('orders', {
    title: 'Order Summaries',
    singular: 'order summary',
    description: 'Order summary records from DRF.',
    group: 'orders',
    icon: 'fa-solid fa-receipt',
    endpoint: '/order-summaries/',
    columns: [['name', 'Order'], ['customer', 'Customer'], ['total', 'Total'], ['status', 'Status']],
    exportable: true,
  }),
  contact: resource('contact', {
    title: 'Contact Messages',
    singular: 'contact message',
    description: 'Customer contact and support messages.',
    group: 'requests',
    icon: 'fa-regular fa-envelope',
    endpoint: '/contactmessage/',
    supportsDetail: false,
    columns: [['name', 'Message'], ['email', 'Email'], ['phone', 'Phone'], ['status', 'Status']],
  }),
  policies: resource('policies', {
    title: 'Policies',
    singular: 'policy',
    description: 'Online store legal and content policies.',
    group: 'store',
    icon: 'fa-solid fa-scale-balanced',
    endpoint: '/policies/',
    columns: [['name', 'Policy'], ['slug', 'Slug'], ['status', 'Status']],
  }),
  banners: resource('banners', {
    title: 'Banners',
    singular: 'banner',
    description: 'Live storefront campaign artwork and calls to action.',
    group: 'media',
    icon: 'fa-regular fa-image',
    endpoint: '/banners/',
    columns: [['name', 'Banner'], ['link', 'Destination'], ['order', 'Position'], ['status', 'Status']],
  }),
  'announcement-bars': resource('announcement-bars', {
    title: 'Announcement Bars',
    singular: 'announcement bar',
    description: 'Top-of-store announcement messages.',
    group: 'media',
    icon: 'fa-solid fa-bullhorn',
    endpoint: '/announcementbars/',
    columns: [['name', 'Announcement'], ['link', 'Destination'], ['order', 'Position'], ['status', 'Status']],
  }),
  'submit-product-requests': resource('submit-product-requests', {
    title: 'Submit Product Requests',
    singular: 'product request',
    description: 'Customer requests for products not currently listed.',
    group: 'requests',
    icon: 'fa-solid fa-clipboard-list',
    endpoint: '/submitproductrequest/',
    supportsDetail: false,
    columns: [['name', 'Request'], ['email', 'Email'], ['product', 'Product'], ['status', 'Status']],
  }),
});

export const adminResourceList = Object.freeze(Object.values(adminResources));

export const getAdminResource = (key) => adminResources[key] || null;
